# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=b'album'),
        ),
    ]
