# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sortno',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='sortno',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
